// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrIP9ZefroU2BAoWyPRT4DXgA17hXsHj4',
    appId: '1:297431408059:web:1659f7bbe049a35d28789e',
    messagingSenderId: '297431408059',
    projectId: 'fastpay-project',
    authDomain: 'fastpay-project.firebaseapp.com',
    storageBucket: 'fastpay-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNftbY1o1JlqZC7G0sZ8XZiceL9_kuE0',
    appId: '1:297431408059:android:25ed3bf85245039528789e',
    messagingSenderId: '297431408059',
    projectId: 'fastpay-project',
    storageBucket: 'fastpay-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKznWSKtW7hrtmdZXMqxnL987U_mZ6pjY',
    appId: '1:297431408059:ios:4a7d9887c83b95f728789e',
    messagingSenderId: '297431408059',
    projectId: 'fastpay-project',
    storageBucket: 'fastpay-project.appspot.com',
    iosClientId: '297431408059-rm4cfa04c5hcu5eq60sjgblb2miituml.apps.googleusercontent.com',
    iosBundleId: 'com.example.fast-pay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKznWSKtW7hrtmdZXMqxnL987U_mZ6pjY',
    appId: '1:297431408059:ios:4a7d9887c83b95f728789e',
    messagingSenderId: '297431408059',
    projectId: 'fastpay-project',
    storageBucket: 'fastpay-project.appspot.com',
    iosClientId: '297431408059-rm4cfa04c5hcu5eq60sjgblb2miituml.apps.googleusercontent.com',
    iosBundleId: 'com.example.fast-pay',
  );
}
